### ISSUE TITLE
key presses that cannot be interpreted as characters crash the building menu

### ISSUE THREAD

**Issue by smaria** [Nanoseb/XKCDLand#14]

**Comment by Nanoseb** [comment]
see src/assets/display.py 
(not sure it is the right place to put that though)

**Comment by Nanoseb** [comment]
ah no, you probably prefer pygame.K_a -> "a"
so not sure what is the best to achieve that

**Comment by Nanoseb** [comment]
ah nevermind, I didn't read properly the issue

**Comment by smaria** [comment]
using pygame.key.name(pygame.K_a)
