### ISSUE TITLE
Figure out how to submit

### ISSUE THREAD

**Issue by smaria** [Nanoseb/XKCDLand#8]
Make sure you have all your files ready to be uploaded.There are many ways to do this, the simplest is if your files just need to be downloaded to run you can submit a zip file for players to download. Alternatively if you are able to upload the following options your game can play in browser;

flash game (.swf files)
javascript (.jar files)
unity 3D (.unity3d files)
html files
There are many different formats for uploading a game. If you are unsure, feel free to talk to organisers, volunteers and mentors.

https://itch.io/jam/tasjam-for-health/topic/7595/how-to-submit-to-itchio

**Comment by Nanoseb** [comment]
this looks like a possible way of packaging our soft: https://cx-freeze.readthedocs.io/en/latest/
